# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-09 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('cod_categoria', models.IntegerField(primary_key=True, serialize=False)),
                ('dsc_categoria', models.CharField(max_length=45)),
                ('vl_categoria', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                'db_table': 'categoria',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('cod_cliente', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_cliente', models.CharField(blank=True, max_length=45, null=True)),
                ('dat_nascimento', models.DateField(blank=True, null=True)),
                ('sexo', models.CharField(blank=True, max_length=1, null=True)),
            ],
            options={
                'db_table': 'cliente',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Filme',
            fields=[
                ('cod_filme', models.IntegerField(primary_key=True, serialize=False)),
                ('nome_filme', models.CharField(max_length=50)),
                ('dt_compra', models.DateField(blank=True, null=True)),
                ('vl_filme', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('ind_pais', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'filme',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Locacao',
            fields=[
                ('cod_locacao', models.IntegerField(primary_key=True, serialize=False)),
                ('dat_inilocacao', models.DateField()),
                ('dat_fimlocacao', models.DateField(blank=True, null=True)),
                ('vl_multa', models.FloatField(blank=True, null=True)),
            ],
            options={
                'db_table': 'locacao',
                'managed': False,
            },
        ),
    ]
